alter table declaracaoimportacao rename to declaracao_importacao;
alter table destaquencm rename to destaque_ncm;
alter table documentoinstrucaodespacho rename to documento_instrucao_despacho;
alter table listadeclaracoes rename to lista_declaracoes;

/*Adição*/
alter table adicao rename column adicao_id to id;
alter table adicao rename column declaracaoimportacao_id to declaracao_importacao_id;
alter table adicao rename column cidevaloraliquotaespecifica to cide_valor_aliquota_especifica;
alter table adicao rename column cidevalordevido to cide_valor_devido;
alter table adicao rename column cidevalorrecolher to cide_valor_recolher;
alter table adicao rename column codigorelacaocompradorvendedor to codigo_relacao_comprador_vendedor;
alter table adicao rename column codigovinculocompradorvendedor to codigo_vinculo_comprador_vendedor;
alter table adicao rename column cofinsaliquotaadvalorem to cofins_aliquota_advalorem;
alter table adicao rename column cofinsaliquotaespecificaquantidadeunidade to cofins_aliquota_especifica_quantidade_unidade;
alter table adicao rename column cofinsaliquotaespecificavalor to cofins_aliquota_especifica_valor;
alter table adicao rename column cofinsaliquotareduzida to cofins_aliquota_reduzida;
alter table adicao rename column cofinsaliquotavalordevido to cofins_aliquota_valor_devido;
alter table adicao rename column cofinsaliquotavalorrecolher to cofins_aliquota_valor_recolher;
alter table adicao rename column condicaovendaincoterm to condicao_venda_incoterm;
alter table adicao rename column condicaovendalocal to condicao_venda_local;
alter table adicao rename column condicaovendametodovaloracaocodigo to condicao_venda_metodo_valor_acao_codigo;
alter table adicao rename column condicaovendametodovaloracaonome to condicao_venda_metodo_valor_acao_nome;
alter table adicao rename column condicaovendamoedacodigo to condicao_venda_moeda_codigo;
alter table adicao rename column condicaovendamoedanome to condicao_venda_moeda_nome;
alter table adicao rename column condicaovendavalormoeda to condicao_venda_valor_moeda;
alter table adicao rename column condicaovendavalorreais to condicao_venda_valor_reais;
alter table adicao rename column dadoscambiaiscoberturacambialcodigo to dados_cambiais_cobertura_cambial_codigo;
alter table adicao rename column dadoscambiaiscoberturacambialnome to dados_cambiais_cobertura_cambial_nome;
alter table adicao rename column dadoscambiaisinstituicaofinanciadoracodigo to dados_cambiais_instituicao_financiadora_codigo;
alter table adicao rename column dadoscambiaisinstituicaofinanciadoranome to dados_cambiais_instituicao_financiadora_nome;
alter table adicao rename column dadoscambiaismotivosemcoberturacodigo to dados_cambiais_motivo_sem_cobertura_codigo;
alter table adicao rename column dadoscambiaismotivosemcoberturanome to dados_cambiais_motivo_sem_cobertura_nome;
alter table adicao rename column dadoscambiaisvalorrealcambio to dados_cambiais_valor_real_cambio;
alter table adicao rename column dadoscargapaisprocedenciacodigo to dados_carga_pais_procedencia_codigo;
alter table adicao rename column dadoscargaurfentradacodigo to dados_carga_urf_entrada_codigo;
alter table adicao rename column dadoscargaviatransportecodigo to dados_carga_via_transporte_codigo;
alter table adicao rename column dadosmercadoriaaplicacao to dados_mercadoria_aplicacao;
alter table adicao rename column dadosmercadoriacodigonaladincca to dados_mercadoria_codigo_naladi_ncca;
alter table adicao rename column dadosmercadoriacodigonaladish to dados_mercadoria_codigo_naladish;
alter table adicao rename column dadosmercadoriacodigoncm to dados_mercadoria_codigo_ncm;
alter table adicao rename column dadosmercadoriacondicao to dados_mercadoria_condicao;
alter table adicao rename column dadosmercadoriamedidaestatisticaquantidade to dados_mercadoria_medida_estatistica_quantidade;
alter table adicao rename column dadosmercadoriamedidaestatisticaunidade to dados_mercadoria_medida_estatistica_unidade;
alter table adicao rename column dadosmercadorianomencm to dados_mercadoria_nome_ncm;
alter table adicao rename column dadosmercadoriapesoliquido to dados_mercadoria_peso_liquido;
alter table adicao rename column dcrcoeficientereducao to dcr_coeficiente_reducao;
alter table adicao rename column dcridentificacao to dcr_identificacao;
alter table adicao rename column dcrvalordevido to dcr_valor_devido;
alter table adicao rename column dcrvalordolar to dcr_valor_dolar;
alter table adicao rename column dcrvalorreal to dcr_valor_real;
alter table adicao rename column dcrvalorrecolher to dcr_valor_recolher;
alter table adicao rename column fabricantecidade to fabricante_cidade;
alter table adicao rename column fabricantecomplemento to fabricante_complemento;
alter table adicao rename column fabricanteestado to fabricante_estado;
alter table adicao rename column fabricantelogradouro to fabricante_logradouro;
alter table adicao rename column fabricantenome to fabricante_nome;
alter table adicao rename column fabricantenumero to fabricante_numero;
alter table adicao rename column fornecedorcidade to fornecedor_cidade;
alter table adicao rename column fornecedorcomplemento to fornecedor_complemento;
alter table adicao rename column fornecedorlogradouro to fornecedor_logradouro;
alter table adicao rename column fornecedornome to fornecedor_nome;
alter table adicao rename column fornecedornumero to fornecedor_numero;
alter table adicao rename column fretemoedanegociadacodigo to frete_moeda_negociada_codigo;
alter table adicao rename column fretevalormoedanegociada to frete_valor_moeda_negociada;
alter table adicao rename column fretevalorreais to frete_valor_reais;
alter table adicao rename column iiacordotarifariotipocodigo to ii_acordo_tarifario_tipo_codigo;
alter table adicao rename column iialiquotaacordo to ii_aliquota_acordo;
alter table adicao rename column iialiquotaadvalorem to ii_aliquota_advalorem;
alter table adicao rename column iialiquotapercentualreducao to ii_aliquota_percentual_reducao;
alter table adicao rename column iialiquotareduzida to ii_aliquota_reduzida;
alter table adicao rename column iialiquotavalorcalculado to ii_aliquota_valor_calculado;
alter table adicao rename column iialiquotavalordevido to ii_aliquota_valor_devido;
alter table adicao rename column iialiquotavalorrecolher to ii_aliquota_valor_recolher;
alter table adicao rename column iialiquotavalorreduzido to ii_aliquota_valor_reduzido;
alter table adicao rename column iibasecalculo to ii_base_calculo;
alter table adicao rename column iiextarifarioatolegalano to ii_ex_tarifario_ato_legal_ano;
alter table adicao rename column iiextarifarioatolegalcodigo to ii_ex_tarifario_ato_legal_codigo;
alter table adicao rename column iiextarifarioatolegalex to ii_ex_tarifario_ato_legal_ex;
alter table adicao rename column iiextarifarioatolegalnumero to ii_ex_tarifario_ato_legal_numero;
alter table adicao rename column iiextarifarioatolegalorgaoemissor to ii_ex_tarifario_ato_legal_orgao_emissor;
alter table adicao rename column iifundamentolegalcodigo to ii_fundamento_legal_codigo;
alter table adicao rename column iimotivoadmissaotemporariacodigo to ii_motivo_admissao_temporaria_codigo;
alter table adicao rename column iiregimetributacaocodigo to ii_regime_tributacao_codigo;
alter table adicao rename column iiregimetributacaonome to ii_regime_tributacao_nome;
alter table adicao rename column ipialiquotaadvalorem to ipi_aliquota_advalorem;
// TODO FIXME ipi_aliquota_especifica_capacidade_recipciente
alter table adicao rename column ipialiquotaespecificacapacidaderecipciente to ipi_aliquota_especifica_capacidade_recipciente;
alter table adicao rename column ipialiquotaespecificaquantidadeunidademedida to ipi_aliquota_especifica_quantidade_unidade_medida;
alter table adicao rename column ipialiquotaespecificatiporecipientecodigo to ipi_aliquota_especifica_tipo_recipiente_codigo;
alter table adicao rename column ipialiquotaespecificavalorunidademedida to ipi_aliquota_especifica_valor_unidade_medida;
alter table adicao rename column ipialiquotanotacomplementartipi to ipi_aliquota_nota_complementar_tipi;
alter table adicao rename column ipialiquotareduzida to ipi_aliquota_reduzida;
alter table adicao rename column ipialiquotavalordevido to ipi_aliquota_valor_devido;
alter table adicao rename column ipialiquotavalorrecolher to ipi_aliquota_valor_recolher;
alter table adicao rename column ipiregimetributacaocodigo to ipi_regime_tributacao_codigo;
alter table adicao rename column ipiregimetributacaonome to ipi_regime_tributacao_nome;
alter table adicao rename column numeroadicao to numero_adicao;
alter table adicao rename column numerodi to numero_di;
alter table adicao rename column numeroli to numero_li;
alter table adicao rename column paisaquisicaomercadoriacodigo to pais_aquisicao_mercadoria_codigo;
alter table adicao rename column paisaquisicaomercadorianome to pais_aquisicao_mercadoria_nome;
alter table adicao rename column paisorigemmercadoriacodigo to pais_origem_mercadoria_codigo;
alter table adicao rename column paisorigemmercadorianome to pais_origem_mercadoria_nome;
alter table adicao rename column piscofinsbasecalculoaliquotaicms to pis_cofins_base_calculo_aliquota_icms;
alter table adicao rename column piscofinsbasecalculofundamentolegalcodigo to pis_cofins_base_calculo_fundamento_legal_codigo;
alter table adicao rename column piscofinsbasecalculopercentualreducao to pis_cofins_base_calculo_percentual_reducao;
alter table adicao rename column piscofinsbasecalculovalor to pis_cofins_base_calculo_valor;
alter table adicao rename column piscofinsfundamentolegalreducaocodigo to pis_cofins_fundamento_legal_reducao_codigo;
alter table adicao rename column piscofinsregimetributacaocodigo to pis_cofins_regime_tributacao_codigo;
alter table adicao rename column piscofinsregimetributacaonome to pis_cofins_regime_tributacao_nome;
alter table adicao rename column pispasepaliquotaadvalorem to pis_pasep_aliquota_advalorem;
alter table adicao rename column pispasepaliquotaespecificaquantidadeunidade to pis_pasep_aliquota_especifica_quantidade_unidade;
alter table adicao rename column pispasepaliquotaespecificavalor to pis_pasep_aliquota_especifica_valor;
alter table adicao rename column pispasepaliquotareduzida to pis_pasep_aliquota_reduzida;
alter table adicao rename column pispasepaliquotavalordevido to pis_pasep_aliquota_valor_devido;
alter table adicao rename column pispasepaliquotavalorrecolher to pis_pasep_aliquota_valor_recolher;
alter table adicao rename column relacaocompradorvendedor to relacao_comprador_vendedor;
alter table adicao rename column seguromoedanegociadacodigo to seguro_moeda_negociada_codigo;
alter table adicao rename column segurovalormoedanegociada to seguro_valor_moeda_negociada;
alter table adicao rename column segurovalorreais to seguro_valor_reais;
alter table adicao rename column sequencialretificacao to sequencial_retificacao;
alter table adicao rename column valormultaarecolher to valor_multa_a_recolher;
alter table adicao rename column valormultaarecolherajustado to valor_multa_a_recolher_ajustado;
alter table adicao rename column valorreaisfreteinternacional to valor_reais_frete_internacional;
alter table adicao rename column valorreaissegurointernacional to valor_reais_seguro_internacional;
alter table adicao rename column valortotalcondicaovenda to valor_total_condicao_venda;
alter table adicao rename column vinculocompradorvendedor to vinculo_comprador_vendedor;
alter table adicao rename column destaquencm_id to destaque_ncm_id;
/*Adição*/

/*Declaração de Importação*/
alter table declaracao_importacao rename column declaracaoimportacao_id to id;
alter table declaracao_importacao rename column listadeclaracoes_id to lista_declaracoes_id;
alter table declaracao_importacao rename column armazenamentorecintoaduaneirocodigo to armazenamento_recinto_aduaneiro_codigo;
alter table declaracao_importacao rename column armazenamentorecintoaduaneironome to armazenamento_recinto_aduaneiro_nome;
alter table declaracao_importacao rename column armazenamentosetor to armazenamento_setor;
alter table declaracao_importacao rename column canalselecaoparametrizada to canal_selecao_parametrizada;
alter table declaracao_importacao rename column caracterizacaooperacaocodigotipo to caracterizacao_operacao_codigo_tipo;
alter table declaracao_importacao rename column caracterizacaooperacaodescricaotipo to caracterizacao_operacao_descricao_tipo;
alter table declaracao_importacao rename column cargadatachegada to carga_data_chegada;
alter table declaracao_importacao rename column carganumeroagente to carga_numero_agente;
alter table declaracao_importacao rename column cargapaisprocedenciacodigo to carga_pais_procedencia_codigo;
alter table declaracao_importacao rename column cargapaisprocedencianome to carga_pais_procedencia_nome;
alter table declaracao_importacao rename column cargapesobruto to carga_peso_bruto;
alter table declaracao_importacao rename column cargapesoliquido to carga_peso_liquido;
alter table declaracao_importacao rename column cargaurfentradacodigo to carga_urf_entrada_codigo;
alter table declaracao_importacao rename column cargaurfentradanome to carga_urf_entrada_nome;
alter table declaracao_importacao rename column conhecimentocargaembarquedata to conhecimento_carga_embarque_data;
alter table declaracao_importacao rename column conhecimentocargaembarquelocal to conhecimento_carga_embarque_local;
alter table declaracao_importacao rename column conhecimentocargaid to conhecimento_carga_id;
alter table declaracao_importacao rename column conhecimentocargaidmaster to conhecimento_carga_id_master;
alter table declaracao_importacao rename column conhecimentocargatipocodigo to conhecimento_carga_tipo_codigo;
alter table declaracao_importacao rename column conhecimentocargatiponome to conhecimento_carga_tipo_nome;
alter table declaracao_importacao rename column conhecimentocargautilizacao to conhecimento_carga_utilizacao;
alter table declaracao_importacao rename column conhecimentocargautilizacaonome to conhecimento_carga_utilizacao_nome;
alter table declaracao_importacao rename column datadesembaraco to data_desembaraco;
alter table declaracao_importacao rename column dataregistro to data_registro;
alter table declaracao_importacao rename column documentochegadacargacodigotipo to documento_chegada_carga_codigo_tipo;
alter table declaracao_importacao rename column documentochegadacarganome to documento_chegada_carga_nome;
alter table declaracao_importacao rename column documentochegadacarganumero to documento_chegada_carga_numero;
alter table declaracao_importacao rename column fretecollect to frete_collect;
alter table declaracao_importacao rename column freteemterritorionacional to frete_em_territorio_nacional;
alter table declaracao_importacao rename column fretemoedanegociadacodigo to frete_moeda_negociada_codigo;
alter table declaracao_importacao rename column fretemoedanegociadanome to frete_moeda_negociada_nome;
alter table declaracao_importacao rename column freteprepaid to frete_prepaid;
alter table declaracao_importacao rename column fretetotaldolares to frete_total_dolares;
alter table declaracao_importacao rename column fretetotalmoeda to frete_total_moeda;
alter table declaracao_importacao rename column fretetotalreais to frete_total_reais;
alter table declaracao_importacao rename column importadorcodigotipo to importador_codigo_tipo;
alter table declaracao_importacao rename column importadorcpfrepresentantelegal to importador_cpf_representante_legal;
alter table declaracao_importacao rename column importadorenderecobairro to importador_endereco_bairro;
alter table declaracao_importacao rename column importadorenderecocep to importador_endereco_cep;
alter table declaracao_importacao rename column importadorenderecocomplemento to importador_endereco_complemento;
alter table declaracao_importacao rename column importadorenderecologradouro to importador_endereco_logradouro;
alter table declaracao_importacao rename column importadorenderecomunicipio to importador_endereco_municipio;
alter table declaracao_importacao rename column importadorendereconumero to importador_endereco_numero;
alter table declaracao_importacao rename column importadorenderecouf to importador_endereco_uf;
alter table declaracao_importacao rename column importadornome to importador_nome;
alter table declaracao_importacao rename column importadornomerepresentantelegal to importador_nome_representante_legal;
alter table declaracao_importacao rename column importadornumero to importador_numero;
alter table declaracao_importacao rename column importadornumerotelefone to importador_numero_telefone;
alter table declaracao_importacao rename column informacaocomplementar to informacao_complementar;
alter table declaracao_importacao rename column localdescargatotaldolares to local_descarga_total_dolares;
alter table declaracao_importacao rename column localdescargatotalreais to local_descarga_total_reais;
alter table declaracao_importacao rename column localembarquetotaldolares to local_embarque_total_dolares;
alter table declaracao_importacao rename column localembarquetotalreais to local_embarque_total_reais;
alter table declaracao_importacao rename column modalidadedespachocodigo to modalidade_despacho_codigo
alter table declaracao_importacao rename column modalidadedespachonome to modalidade_despacho_nome;
alter table declaracao_importacao rename column numerodi to numero_di;
alter table declaracao_importacao rename column operacaofundap to operacao_fundap;
alter table declaracao_importacao rename column seguromoedanegociadacodigo to seguro_moeda_negociada_codigo;
alter table declaracao_importacao rename column seguromoedanegociadanome to seguro_moeda_negociada_nome;
alter table declaracao_importacao rename column segurototaldolares to seguro_total_dolares;
alter table declaracao_importacao rename column segurototalmoedanegociada to seguro_total_moeda_negociada;
alter table declaracao_importacao rename column segurototalreais to seguro_total_reais;
alter table declaracao_importacao rename column sequencialretificacao to sequencial_retificacao;
alter table declaracao_importacao rename column situacaoentregacarga to situacao_entrega_carga;
alter table declaracao_importacao rename column tipodeclaracaocodigo to tipo_declaracao_codigo;
alter table declaracao_importacao rename column tipodeclaracaonome to tipo_declaracao_nome;
alter table declaracao_importacao rename column totaladicoes to total_adicoes;
alter table declaracao_importacao rename column urfdespachocodigo to urf_despacho_codigo;
alter table declaracao_importacao rename column urfdespachonome to urf_despacho_nome;
alter table declaracao_importacao rename column valortotalmultaarecolherajustado to valor_total_multa_a_recolher_ajustado;
alter table declaracao_importacao rename column viatransportecodigo to via_transporte_codigo;
alter table declaracao_importacao rename column viatransportemultimodal to via_transporte_multimodal;
alter table declaracao_importacao rename column viatransportenome to via_transporte_nome;
alter table declaracao_importacao rename column viatransportenometransportador to via_transporte_nome_transportador;
alter table declaracao_importacao rename column viatransportepaistransportadorcodigo to via_transporte_pais_transportador_codigo;
alter table declaracao_importacao rename column viatransportepaistransportadornome to via_transporte_pais_transportador_nome;
alter table declaracao_importacao rename column documentoinstrucaodespacho_id to documento_instrucao_despacho_id;
/*Declaração de Importação*/

/*Pagamento*/
alter table pagamento rename column pagamento_id to id;
alter table pagamento rename column declaracaoimportacao_id to declaracao_importacao_id;
alter table pagamento rename column agenciapagamento to agencia_pagamento;
alter table pagamento rename column bancopagamento to banco_pagamento;
alter table pagamento rename column codigoreceita to codigo_receita;
alter table pagamento rename column codigotipopagamento to codigo_tipo_pagamento;
alter table pagamento rename column contapagamento to conta_pagamento;
alter table pagamento rename column datapagamento to data_pagamento;
alter table pagamento rename column nometipopagamento to nome_tipo_pagamento;
alter table pagamento rename column numeroretificacao to numero_retificacao;
alter table pagamento rename column valorjurosencargos to valor_juros_encargos;
alter table pagamento rename column valormulta to valor_multa;
alter table pagamento rename column valorreceita to valor_receita;
/*Pagamento*/

/*Mercadoria*/
alter table mercadoria rename column mercadoria_id to id;
alter table mercadoria rename column descricaomercadoria to descricao_mercadoria;
alter table mercadoria rename column numerosequencialitem to numero_sequencial_item;
alter table mercadoria rename column unidademedida to unidade_medida;
alter table mercadoria rename column valorunitario to valor_unitario;
/*Mercadoria*/

/*Lista de Declarações*/
alter table lista_declaracoes rename column declaracaoimportacao_id to declaracao_importacao_id;
alter table lista_declaracoes rename column lista_declaracoes_id to id;
/*Lista de Declarações*/

/*ICMS*/
alter table icms rename column icms_id to id;
alter table icms rename column declaracaoimportacao_id to declaracao_importacao_id;
alter table icms rename column agenciaicms to agencia_icms;
alter table icms rename column bancoicms to banco_icms;
alter table icms rename column codigotiporecolhimentoicms to codigo_tipo_recolhimento_icms;
alter table icms rename column cpfresponsavelregistro to cpf_responsavel_registro;
alter table icms rename column dataregistro to data_registro;
alter table icms rename column horaregistro to hora_registro;
alter table icms rename column nometiporecolhimentoicms to nome_tipo_recolhimento_icms;
alter table icms rename column numerosequencialicms to numero_sequencial_icms;
alter table icms rename column uficms to uf_icms;
alter table icms rename column valortotalicms to valor_total_icms;
/*ICMS*/

/*Embalagem*/
alter table embalagem rename column embalagem_id to id;
alter table embalagem rename column declaracaoimportacao_id to declaracao_importacao_id;
alter table embalagem rename column codigotipoembalagem to codigo_tipo_embalagem;
alter table embalagem rename column nomeembalagem to nome_embalagem;
alter table embalagem rename column quantidadevolume to quantidade_volume;
/*Embalagem*/

/*Destaque NCM*/
alter table destaque_ncm rename column destaquencm_id to destaque_ncm_id;
alter table destaque_ncm rename column numerodestaque to numero_destaque;
/*Destaque NCM*/

/*Documento Instrução Despacho*/
alter table documento_instrucao_despacho rename column documentoinstrucaodespacho_id to id;
alter table documento_instrucao_despacho rename column declaracaoimportacao_id to declaracao_importacao_id;
alter table documento_instrucao_despacho rename column codigotipodocumentodespacho to codigo_tipo_documento_despacho;
alter table documento_instrucao_despacho rename column nomedocumentodespacho to nome_documento_despacho;
alter table documento_instrucao_despacho rename column numerodocumentodespacho to numero_documento_despacho;
/*Documento Instrução Despacho*/

/*ICMS*/
ALTER TABLE icms ALTER COLUMN id TYPE varchar(255) USING id::varchar(255);
ALTER TABLE icms ALTER COLUMN declaracao_importacao_id TYPE varchar(255) USING declaracao_importacao_id::varchar(255);
ALTER TABLE icms ALTER COLUMN agencia_icms TYPE varchar(255) USING agencia_icms::varchar(255);
ALTER TABLE icms ALTER COLUMN banco_icms TYPE varchar(255) USING banco_icms::varchar(255);
ALTER TABLE icms ALTER COLUMN codigo_tipo_recolhimento_icms TYPE varchar(255) USING codigo_tipo_recolhimento_icms::varchar(255);
ALTER TABLE icms ALTER COLUMN cpf_responsavel_registro TYPE varchar(255) USING cpf_responsavel_registro::varchar(255);
ALTER TABLE icms ALTER COLUMN data_registro TYPE varchar(255) USING data_registro::varchar(255);
ALTER TABLE icms ALTER COLUMN hora_registro TYPE varchar(255) USING hora_registro::varchar(255);
ALTER TABLE icms ALTER COLUMN nome_tipo_recolhimento_icms TYPE varchar(255) USING nome_tipo_recolhimento_icms::varchar(255);
ALTER TABLE icms ALTER COLUMN numero_sequencial_icms TYPE varchar(255) USING numero_sequencial_icms::varchar(255);
ALTER TABLE icms ALTER COLUMN uf_icms TYPE varchar(255) USING uf_icms::varchar(255);
ALTER TABLE icms ALTER COLUMN valor_total_icms TYPE varchar(255) USING valor_total_icms::varchar(255);
/*ICMS*/

/*Destaque NCM*/
alter table destaque_ncm drop constraint destaquencm_destaquencm_id_check;
alter table destaque_ncm drop constraint destaquencm_adicao_id_check;
ALTER TABLE destaque_ncm ALTER COLUMN document_id TYPE varchar(255) USING document_id::varchar(255);
ALTER TABLE destaque_ncm ALTER COLUMN destaque_ncm_id TYPE varchar(255) USING destaque_ncm_id::varchar(255);
ALTER TABLE destaque_ncm ALTER COLUMN adicao_id TYPE varchar(255) USING adicao_id::varchar(255);
ALTER TABLE destaque_ncm ALTER COLUMN numero_destaque TYPE varchar(255) USING numero_destaque::varchar(255);
/*Destaque NCM*/

/*Adição*/
alter table adicao drop constraint adicao_adicao_id_check;
alter table adicao drop constraint adicao_declaracaoimportacao_id_check;
alter table adicao drop constraint adicao_mercadoria_id_check;
alter table adicao drop constraint adicao_destaquencm_id_check;
ALTER TABLE adicao ALTER COLUMN document_id TYPE varchar(255) USING document_id::varchar(255);
ALTER TABLE adicao ALTER COLUMN id TYPE varchar(255) USING id::varchar(255);
ALTER TABLE adicao ALTER COLUMN declaracao_importacao_id TYPE varchar(255) USING declaracao_importacao_id::varchar(255);
ALTER TABLE adicao ALTER COLUMN cide_valor_aliquota_especifica TYPE varchar(255) USING cide_valor_aliquota_especifica::varchar(255);
ALTER TABLE adicao ALTER COLUMN cidevalordevido TYPE varchar(255) USING cidevalordevido::varchar(255);
ALTER TABLE adicao ALTER COLUMN cide_valor_recolher TYPE varchar(255) USING cide_valor_recolher::varchar(255);
ALTER TABLE adicao ALTER COLUMN codigo_relacao_comprador_vendedor TYPE varchar(255) USING codigo_relacao_comprador_vendedor::varchar(255);
ALTER TABLE adicao ALTER COLUMN codigo_vinculo_comprador_vendedor TYPE varchar(255) USING codigo_vinculo_comprador_vendedor::varchar(255);
ALTER TABLE adicao ALTER COLUMN cofins_aliquota_advalorem TYPE varchar(255) USING cofins_aliquota_advalorem::varchar(255);
ALTER TABLE adicao ALTER COLUMN cofins_aliquota_especifica_quantidade_unidade TYPE varchar(255) USING cofins_aliquota_especifica_quantidade_unidade::varchar(255);
ALTER TABLE adicao ALTER COLUMN cofins_aliquota_especifica_valor TYPE varchar(255) USING cofins_aliquota_especifica_valor::varchar(255);
ALTER TABLE adicao ALTER COLUMN cofins_aliquota_reduzida TYPE varchar(255) USING cofins_aliquota_reduzida::varchar(255);
ALTER TABLE adicao ALTER COLUMN cofins_aliquota_valor_devido TYPE varchar(255) USING cofins_aliquota_valor_devido::varchar(255);
ALTER TABLE adicao ALTER COLUMN cofins_aliquota_valor_recolher TYPE varchar(255) USING cofins_aliquota_valor_recolher::varchar(255);
ALTER TABLE adicao ALTER COLUMN condicao_venda_incoterm TYPE varchar(255) USING condicao_venda_incoterm::varchar(255);
ALTER TABLE adicao ALTER COLUMN condicao_venda_local TYPE varchar(255) USING condicao_venda_local::varchar(255);
ALTER TABLE adicao ALTER COLUMN condicao_venda_metodo_valor_acao_codigo TYPE varchar(255) USING condicao_venda_metodo_valor_acao_codigo::varchar(255);
ALTER TABLE adicao ALTER COLUMN condicao_venda_metodo_valor_acao_nome TYPE varchar(255) USING condicao_venda_metodo_valor_acao_nome::varchar(255);
ALTER TABLE adicao ALTER COLUMN condicao_venda_moeda_codigo TYPE varchar(255) USING condicao_venda_moeda_codigo::varchar(255);
ALTER TABLE adicao ALTER COLUMN condicao_venda_moeda_nome TYPE varchar(255) USING condicao_venda_moeda_nome::varchar(255);
ALTER TABLE adicao ALTER COLUMN condicao_venda_valor_moeda TYPE varchar(255) USING condicao_venda_valor_moeda::varchar(255);
ALTER TABLE adicao ALTER COLUMN condicao_venda_valor_reais TYPE varchar(255) USING condicao_venda_valor_reais::varchar(255);
ALTER TABLE adicao ALTER COLUMN dados_cambiais_cobertura_cambial_codigo TYPE varchar(255) USING dados_cambiais_cobertura_cambial_codigo::varchar(255);
ALTER TABLE adicao ALTER COLUMN dados_cambiais_cobertura_cambial_nome TYPE varchar(255) USING dados_cambiais_cobertura_cambial_nome::varchar(255);
ALTER TABLE adicao ALTER COLUMN dados_cambiais_instituicao_financiadora_codigo TYPE varchar(255) USING dados_cambiais_instituicao_financiadora_codigo::varchar(255);
ALTER TABLE adicao ALTER COLUMN dados_cambiais_instituicao_financiadora_nome TYPE varchar(255) USING dados_cambiais_instituicao_financiadora_nome::varchar(255);
ALTER TABLE adicao ALTER COLUMN dados_cambiais_motivo_sem_cobertura_codigo TYPE varchar(255) USING dados_cambiais_motivo_sem_cobertura_codigo::varchar(255);
ALTER TABLE adicao ALTER COLUMN dados_cambiais_motivo_sem_cobertura_nome TYPE varchar(255) USING dados_cambiais_motivo_sem_cobertura_nome::varchar(255);
ALTER TABLE adicao ALTER COLUMN dados_cambiais_valor_real_cambio TYPE varchar(255) USING dados_cambiais_valor_real_cambio::varchar(255);
ALTER TABLE adicao ALTER COLUMN dados_carga_pais_procedencia_codigo TYPE varchar(255) USING dados_carga_pais_procedencia_codigo::varchar(255);
ALTER TABLE adicao ALTER COLUMN dados_carga_urf_entrada_codigo TYPE varchar(255) USING dados_carga_urf_entrada_codigo::varchar(255);
ALTER TABLE adicao ALTER COLUMN dados_carga_via_transporte_codigo TYPE varchar(255) USING dados_carga_via_transporte_codigo::varchar(255);
ALTER TABLE adicao ALTER COLUMN dados_mercadoria_aplicacao TYPE varchar(255) USING dados_mercadoria_aplicacao::varchar(255);
ALTER TABLE adicao ALTER COLUMN dados_mercadoria_codigo_naladi_ncca TYPE varchar(255) USING dados_mercadoria_codigo_naladi_ncca::varchar(255);
ALTER TABLE adicao ALTER COLUMN dados_mercadoria_codigo_naladish TYPE varchar(255) USING dados_mercadoria_codigo_naladish::varchar(255);
ALTER TABLE adicao ALTER COLUMN dados_mercadoria_codigo_ncm TYPE varchar(255) USING dados_mercadoria_codigo_ncm::varchar(255);
ALTER TABLE adicao ALTER COLUMN dados_mercadoria_condicao TYPE varchar(255) USING dados_mercadoria_condicao::varchar(255);
ALTER TABLE adicao ALTER COLUMN dados_mercadoria_medida_estatistica_quantidade TYPE varchar(255) USING dados_mercadoria_medida_estatistica_quantidade::varchar(255);
ALTER TABLE adicao ALTER COLUMN dados_mercadoria_medida_estatistica_unidade TYPE varchar(255) USING dados_mercadoria_medida_estatistica_unidade::varchar(255);
ALTER TABLE adicao ALTER COLUMN dados_mercadoria_nome_ncm TYPE varchar(255) USING dados_mercadoria_nome_ncm::varchar(255);
ALTER TABLE adicao ALTER COLUMN dados_mercadoria_peso_liquido TYPE varchar(255) USING dados_mercadoria_peso_liquido::varchar(255);
ALTER TABLE adicao ALTER COLUMN dcr_coeficiente_reducao TYPE varchar(255) USING dcr_coeficiente_reducao::varchar(255);
ALTER TABLE adicao ALTER COLUMN dcr_identificacao TYPE varchar(255) USING dcr_identificacao::varchar(255);
ALTER TABLE adicao ALTER COLUMN dcr_valor_devido TYPE varchar(255) USING dcr_valor_devido::varchar(255);
ALTER TABLE adicao ALTER COLUMN dcr_valor_dolar TYPE varchar(255) USING dcr_valor_dolar::varchar(255);
ALTER TABLE adicao ALTER COLUMN dcr_valor_real TYPE varchar(255) USING dcr_valor_real::varchar(255);
ALTER TABLE adicao ALTER COLUMN dcr_valor_recolher TYPE varchar(255) USING dcr_valor_recolher::varchar(255);
ALTER TABLE adicao ALTER COLUMN fabricante_cidade TYPE varchar(255) USING fabricante_cidade::varchar(255);
ALTER TABLE adicao ALTER COLUMN fabricante_complemento TYPE varchar(255) USING fabricante_complemento::varchar(255);
ALTER TABLE adicao ALTER COLUMN fabricante_estado TYPE varchar(255) USING fabricante_estado::varchar(255);
ALTER TABLE adicao ALTER COLUMN fabricante_logradouro TYPE varchar(255) USING fabricante_logradouro::varchar(255);
ALTER TABLE adicao ALTER COLUMN fabricante_nome TYPE varchar(255) USING fabricante_nome::varchar(255);
ALTER TABLE adicao ALTER COLUMN fabricante_numero TYPE varchar(255) USING fabricante_numero::varchar(255);
ALTER TABLE adicao ALTER COLUMN fornecedor_cidade TYPE varchar(255) USING fornecedor_cidade::varchar(255);
ALTER TABLE adicao ALTER COLUMN fornecedor_complemento TYPE varchar(255) USING fornecedor_complemento::varchar(255);
ALTER TABLE adicao ALTER COLUMN fornecedor_logradouro TYPE varchar(255) USING fornecedor_logradouro::varchar(255);
ALTER TABLE adicao ALTER COLUMN fornecedor_nome TYPE varchar(255) USING fornecedor_nome::varchar(255);
ALTER TABLE adicao ALTER COLUMN fornecedor_numero TYPE varchar(255) USING fornecedor_numero::varchar(255);
ALTER TABLE adicao ALTER COLUMN frete_moeda_negociada_codigo TYPE varchar(255) USING frete_moeda_negociada_codigo::varchar(255);
ALTER TABLE adicao ALTER COLUMN frete_valor_moeda_negociada TYPE varchar(255) USING frete_valor_moeda_negociada::varchar(255);
ALTER TABLE adicao ALTER COLUMN frete_valor_reais TYPE varchar(255) USING frete_valor_reais::varchar(255);
ALTER TABLE adicao ALTER COLUMN ii_acordo_tarifario_tipo_codigo TYPE varchar(255) USING ii_acordo_tarifario_tipo_codigo::varchar(255);
ALTER TABLE adicao ALTER COLUMN ii_aliquota_acordo TYPE varchar(255) USING ii_aliquota_acordo::varchar(255);
ALTER TABLE adicao ALTER COLUMN ii_aliquota_advalorem TYPE varchar(255) USING ii_aliquota_advalorem::varchar(255);
ALTER TABLE adicao ALTER COLUMN ii_aliquota_percentual_reducao TYPE varchar(255) USING ii_aliquota_percentual_reducao::varchar(255);
ALTER TABLE adicao ALTER COLUMN ii_aliquota_reduzida TYPE varchar(255) USING ii_aliquota_reduzida::varchar(255);
ALTER TABLE adicao ALTER COLUMN ii_aliquota_valor_calculado TYPE varchar(255) USING ii_aliquota_valor_calculado::varchar(255);
ALTER TABLE adicao ALTER COLUMN ii_aliquota_valor_devido TYPE varchar(255) USING ii_aliquota_valor_devido::varchar(255);
ALTER TABLE adicao ALTER COLUMN ii_aliquota_valor_recolher TYPE varchar(255) USING ii_aliquota_valor_recolher::varchar(255);
ALTER TABLE adicao ALTER COLUMN ii_aliquota_valor_reduzido TYPE varchar(255) USING ii_aliquota_valor_reduzido::varchar(255);
ALTER TABLE adicao ALTER COLUMN ii_base_calculo TYPE varchar(255) USING ii_base_calculo::varchar(255);
ALTER TABLE adicao ALTER COLUMN ii_ex_tarifario_ato_legal_ano TYPE varchar(255) USING ii_ex_tarifario_ato_legal_ano::varchar(255);
ALTER TABLE adicao ALTER COLUMN iiextarifarioatolegalcodigo TYPE varchar(255) USING iiextarifarioatolegalcodigo::varchar(255);
ALTER TABLE adicao ALTER COLUMN ii_ex_tarifario_ato_legal_ex TYPE varchar(255) USING ii_ex_tarifario_ato_legal_ex::varchar(255);
ALTER TABLE adicao ALTER COLUMN ii_ex_tarifario_ato_legal_numero TYPE varchar(255) USING ii_ex_tarifario_ato_legal_numero::varchar(255);
ALTER TABLE adicao ALTER COLUMN ii_ex_tarifario_ato_legal_orgao_emissor TYPE varchar(255) USING ii_ex_tarifario_ato_legal_orgao_emissor::varchar(255);
ALTER TABLE adicao ALTER COLUMN ii_fundamento_legal_codigo TYPE varchar(255) USING ii_fundamento_legal_codigo::varchar(255);
ALTER TABLE adicao ALTER COLUMN ii_motivo_admissao_temporaria_codigo TYPE varchar(255) USING ii_motivo_admissao_temporaria_codigo::varchar(255);
ALTER TABLE adicao ALTER COLUMN ii_regime_tributacao_codigo TYPE varchar(255) USING ii_regime_tributacao_codigo::varchar(255);
ALTER TABLE adicao ALTER COLUMN ii_regime_tributacao_nome TYPE varchar(255) USING ii_regime_tributacao_nome::varchar(255);
ALTER TABLE adicao ALTER COLUMN ipi_aliquota_advalorem TYPE varchar(255) USING ipi_aliquota_advalorem::varchar(255);
ALTER TABLE adicao ALTER COLUMN ipi_aliquota_especifica_capacidade_recipciente TYPE varchar(255) USING ipi_aliquota_especifica_capacidade_recipciente::varchar(255);
ALTER TABLE adicao ALTER COLUMN ipi_aliquota_especifica_quantidade_unidade_medida TYPE varchar(255) USING ipi_aliquota_especifica_quantidade_unidade_medida::varchar(255);
ALTER TABLE adicao ALTER COLUMN ipi_aliquota_especifica_tipo_recipiente_codigo TYPE varchar(255) USING ipi_aliquota_especifica_tipo_recipiente_codigo::varchar(255);
ALTER TABLE adicao ALTER COLUMN ipi_aliquota_especifica_valor_unidade_medida TYPE varchar(255) USING ipi_aliquota_especifica_valor_unidade_medida::varchar(255);
ALTER TABLE adicao ALTER COLUMN ipi_aliquota_nota_complementar_tipi TYPE varchar(255) USING ipi_aliquota_nota_complementar_tipi::varchar(255);
ALTER TABLE adicao ALTER COLUMN ipi_aliquota_reduzida TYPE varchar(255) USING ipi_aliquota_reduzida::varchar(255);
ALTER TABLE adicao ALTER COLUMN ipi_aliquota_valor_devido TYPE varchar(255) USING ipi_aliquota_valor_devido::varchar(255);
ALTER TABLE adicao ALTER COLUMN ipi_aliquota_valor_recolher TYPE varchar(255) USING ipi_aliquota_valor_recolher::varchar(255);
ALTER TABLE adicao ALTER COLUMN ipi_regime_tributacao_codigo TYPE varchar(255) USING ipi_regime_tributacao_codigo::varchar(255);
ALTER TABLE adicao ALTER COLUMN ipi_regime_tributacao_nome TYPE varchar(255) USING ipi_regime_tributacao_nome::varchar(255);
ALTER TABLE adicao ALTER COLUMN numero_adicao TYPE varchar(255) USING numero_adicao::varchar(255);
ALTER TABLE adicao ALTER COLUMN numero_di TYPE varchar(255) USING numero_di::varchar(255);
ALTER TABLE adicao ALTER COLUMN numero_li TYPE varchar(255) USING numero_li::varchar(255);
ALTER TABLE adicao ALTER COLUMN pais_aquisicao_mercadoria_codigo TYPE varchar(255) USING pais_aquisicao_mercadoria_codigo::varchar(255);
ALTER TABLE adicao ALTER COLUMN pais_aquisicao_mercadoria_nome TYPE varchar(255) USING pais_aquisicao_mercadoria_nome::varchar(255);
ALTER TABLE adicao ALTER COLUMN pais_origem_mercadoria_codigo TYPE varchar(255) USING pais_origem_mercadoria_codigo::varchar(255);
ALTER TABLE adicao ALTER COLUMN pais_origem_mercadoria_nome TYPE varchar(255) USING pais_origem_mercadoria_nome::varchar(255);
ALTER TABLE adicao ALTER COLUMN pis_cofins_base_calculo_aliquota_icms TYPE varchar(255) USING pis_cofins_base_calculo_aliquota_icms::varchar(255);
ALTER TABLE adicao ALTER COLUMN pis_cofins_base_calculo_fundamento_legal_codigo TYPE varchar(255) USING pis_cofins_base_calculo_fundamento_legal_codigo::varchar(255);
ALTER TABLE adicao ALTER COLUMN pis_cofins_base_calculo_percentual_reducao TYPE varchar(255) USING pis_cofins_base_calculo_percentual_reducao::varchar(255);
ALTER TABLE adicao ALTER COLUMN pis_cofins_base_calculo_valor TYPE varchar(255) USING pis_cofins_base_calculo_valor::varchar(255);
ALTER TABLE adicao ALTER COLUMN pis_cofins_fundamento_legal_reducao_codigo TYPE varchar(255) USING pis_cofins_fundamento_legal_reducao_codigo::varchar(255);
ALTER TABLE adicao ALTER COLUMN pis_cofins_regime_tributacao_codigo TYPE varchar(255) USING pis_cofins_regime_tributacao_codigo::varchar(255);
ALTER TABLE adicao ALTER COLUMN pis_cofins_regime_tributacao_nome TYPE varchar(255) USING pis_cofins_regime_tributacao_nome::varchar(255);
ALTER TABLE adicao ALTER COLUMN pis_pasep_aliquota_advalorem TYPE varchar(255) USING pis_pasep_aliquota_advalorem::varchar(255);
ALTER TABLE adicao ALTER COLUMN pis_pasep_aliquota_especifica_quantidade_unidade TYPE varchar(255) USING pis_pasep_aliquota_especifica_quantidade_unidade::varchar(255);
ALTER TABLE adicao ALTER COLUMN pis_pasep_aliquota_especifica_valor TYPE varchar(255) USING pis_pasep_aliquota_especifica_valor::varchar(255);
ALTER TABLE adicao ALTER COLUMN pis_pasep_aliquota_reduzida TYPE varchar(255) USING pis_pasep_aliquota_reduzida::varchar(255);
ALTER TABLE adicao ALTER COLUMN pis_pasep_aliquota_valor_devido TYPE varchar(255) USING pis_pasep_aliquota_valor_devido::varchar(255);
ALTER TABLE adicao ALTER COLUMN pis_pasep_aliquota_valor_recolher TYPE varchar(255) USING pis_pasep_aliquota_valor_recolher::varchar(255);
ALTER TABLE adicao ALTER COLUMN relacao_comprador_vendedor TYPE varchar(255) USING relacao_comprador_vendedor::varchar(255);
ALTER TABLE adicao ALTER COLUMN seguro_moeda_negociada_codigo TYPE varchar(255) USING seguro_moeda_negociada_codigo::varchar(255);
ALTER TABLE adicao ALTER COLUMN seguro_valor_moeda_negociada TYPE varchar(255) USING seguro_valor_moeda_negociada::varchar(255);
ALTER TABLE adicao ALTER COLUMN seguro_valor_reais TYPE varchar(255) USING seguro_valor_reais::varchar(255);
ALTER TABLE adicao ALTER COLUMN sequencial_retificacao TYPE varchar(255) USING sequencial_retificacao::varchar(255);
ALTER TABLE adicao ALTER COLUMN valor_multa_a_recolher TYPE varchar(255) USING valor_multa_a_recolher::varchar(255);
ALTER TABLE adicao ALTER COLUMN valor_multa_a_recolher_ajustado TYPE varchar(255) USING valor_multa_a_recolher_ajustado::varchar(255);
ALTER TABLE adicao ALTER COLUMN valor_reais_frete_internacional TYPE varchar(255) USING valor_reais_frete_internacional::varchar(255);
ALTER TABLE adicao ALTER COLUMN valor_reais_seguro_internacional TYPE varchar(255) USING valor_reais_seguro_internacional::varchar(255);
ALTER TABLE adicao ALTER COLUMN valor_total_condicao_venda TYPE varchar(255) USING valor_total_condicao_venda::varchar(255);
ALTER TABLE adicao ALTER COLUMN vinculo_comprador_vendedor TYPE varchar(255) USING vinculo_comprador_vendedor::varchar(255);
ALTER TABLE adicao ALTER COLUMN mercadoria_id TYPE varchar(255) USING mercadoria_id::varchar(255);
ALTER TABLE adicao ALTER COLUMN destaque_ncm_id TYPE varchar(255) USING destaque_ncm_id::varchar(255);
/*Adição*/

/*Mercadoria*/
alter table mercadoria drop constraint mercadoria_mercadoria_id_check;
alter table mercadoria drop constraint mercadoria_adicao_id_check;
ALTER TABLE mercadoria ALTER COLUMN document_id TYPE varchar(255) USING document_id::varchar(255);
ALTER TABLE mercadoria ALTER COLUMN id TYPE varchar(255) USING id::varchar(255);
ALTER TABLE mercadoria ALTER COLUMN adicao_id TYPE varchar(255) USING adicao_id::varchar(255);
ALTER TABLE mercadoria ALTER COLUMN numero_sequencial_item TYPE varchar(255) USING numero_sequencial_item::varchar(255);
ALTER TABLE mercadoria ALTER COLUMN quantidade TYPE varchar(255) USING quantidade::varchar(255);
ALTER TABLE mercadoria ALTER COLUMN unidade_medida TYPE varchar(255) USING unidade_medida::varchar(255);
ALTER TABLE mercadoria ALTER COLUMN valor_unitario TYPE varchar(255) USING valor_unitario::varchar(255);
/*Mercadoria*/


/*Declaração Importacao*/
ALTER TABLE declaracao_importacao ALTER COLUMN document_id TYPE varchar(255) USING document_id::varchar(255);
ALTER TABLE declaracao_importacao ALTER COLUMN id TYPE varchar(255) USING id::varchar(255);
ALTER TABLE declaracao_importacao ALTER COLUMN lista_declaracoes_id TYPE varchar(255) USING lista_declaracoes_id::varchar(255);
ALTER TABLE declaracao_importacao ALTER COLUMN adicao_id TYPE varchar(255) USING adicao_id::varchar(255);
ALTER TABLE declaracao_importacao ALTER COLUMN armazenamento_recinto_aduaneiro_codigo TYPE varchar(255) USING armazenamento_recinto_aduaneiro_codigo::varchar(255);
ALTER TABLE declaracao_importacao ALTER COLUMN armazenamento_recinto_aduaneiro_nome TYPE varchar(255) USING armazenamento_recinto_aduaneiro_nome::varchar(255);
ALTER TABLE declaracao_importacao ALTER COLUMN armazenamento_setor TYPE varchar(255) USING armazenamento_setor::varchar(255);
ALTER TABLE declaracao_importacao ALTER COLUMN canal_selecao_parametrizada TYPE varchar(255) USING canal_selecao_parametrizada::varchar(255);
ALTER TABLE declaracao_importacao ALTER COLUMN caracterizacao_operacao_codigo_tipo TYPE varchar(255) USING caracterizacao_operacao_codigo_tipo::varchar(255);
ALTER TABLE declaracao_importacao ALTER COLUMN caracterizacao_operacao_descricao_tipo TYPE varchar(255) USING caracterizacao_operacao_descricao_tipo::varchar(255);
ALTER TABLE declaracao_importacao ALTER COLUMN carga_data_chegada TYPE varchar(255) USING carga_data_chegada::varchar(255);
ALTER TABLE declaracao_importacao ALTER COLUMN carga_numero_agente TYPE varchar(255) USING carga_numero_agente::varchar(255);
ALTER TABLE declaracao_importacao ALTER COLUMN carga_pais_procedencia_codigo TYPE varchar(255) USING carga_pais_procedencia_codigo::varchar(255);
ALTER TABLE declaracao_importacao ALTER COLUMN carga_pais_procedencia_nome TYPE varchar(255) USING carga_pais_procedencia_nome::varchar(255);
ALTER TABLE declaracao_importacao ALTER COLUMN carga_peso_bruto TYPE varchar(255) USING carga_peso_bruto::varchar(255);
ALTER TABLE declaracao_importacao ALTER COLUMN carga_peso_liquido TYPE varchar(255) USING carga_peso_liquido::varchar(255);
ALTER TABLE declaracao_importacao ALTER COLUMN carga_urf_entrada_codigo TYPE varchar(255) USING carga_urf_entrada_codigo::varchar(255);
ALTER TABLE declaracao_importacao ALTER COLUMN carga_urf_entrada_nome TYPE varchar(255) USING carga_urf_entrada_nome::varchar(255);
ALTER TABLE declaracao_importacao ALTER COLUMN conhecimento_carga_embarque_data TYPE varchar(255) USING conhecimento_carga_embarque_data::varchar(255);
ALTER TABLE declaracao_importacao ALTER COLUMN conhecimento_carga_embarque_local TYPE varchar(255) USING conhecimento_carga_embarque_local::varchar(255);
ALTER TABLE declaracao_importacao ALTER COLUMN conhecimento_carga_id TYPE varchar(255) USING conhecimento_carga_id::varchar(255);
ALTER TABLE declaracao_importacao ALTER COLUMN conhecimento_carga_id_master TYPE varchar(255) USING conhecimento_carga_id_master::varchar(255);
ALTER TABLE declaracao_importacao ALTER COLUMN conhecimento_carga_tipo_codigo TYPE varchar(255) USING conhecimento_carga_tipo_codigo::varchar(255);
ALTER TABLE declaracao_importacao ALTER COLUMN conhecimento_carga_tipo_nome TYPE varchar(255) USING conhecimento_carga_tipo_nome::varchar(255);
ALTER TABLE declaracao_importacao ALTER COLUMN conhecimento_carga_utilizacao TYPE varchar(255) USING conhecimento_carga_utilizacao::varchar(255);
ALTER TABLE declaracao_importacao ALTER COLUMN conhecimento_carga_utilizacao_nome TYPE varchar(255) USING conhecimento_carga_utilizacao_nome::varchar(255);
ALTER TABLE declaracao_importacao ALTER COLUMN data_desembaraco TYPE varchar(255) USING data_desembaraco::varchar(255);
ALTER TABLE declaracao_importacao ALTER COLUMN data_registro TYPE varchar(255) USING data_registro::varchar(255);
ALTER TABLE declaracao_importacao ALTER COLUMN documento_chegada_carga_codigo_tipo TYPE varchar(255) USING documento_chegada_carga_codigo_tipo::varchar(255);
ALTER TABLE declaracao_importacao ALTER COLUMN documento_chegada_carga_nome TYPE varchar(255) USING documento_chegada_carga_nome::varchar(255);
ALTER TABLE declaracao_importacao ALTER COLUMN documento_chegada_carga_numero TYPE varchar(255) USING documento_chegada_carga_numero::varchar(255);
ALTER TABLE declaracao_importacao ALTER COLUMN frete_collect TYPE varchar(255) USING frete_collect::varchar(255);
ALTER TABLE declaracao_importacao ALTER COLUMN frete_em_territorio_nacional TYPE varchar(255) USING frete_em_territorio_nacional::varchar(255);
ALTER TABLE declaracao_importacao ALTER COLUMN frete_moeda_negociada_codigo TYPE varchar(255) USING frete_moeda_negociada_codigo::varchar(255);
ALTER TABLE declaracao_importacao ALTER COLUMN frete_moeda_negociada_nome TYPE varchar(255) USING frete_moeda_negociada_nome::varchar(255);
ALTER TABLE declaracao_importacao ALTER COLUMN frete_prepaid TYPE varchar(255) USING frete_prepaid::varchar(255);
ALTER TABLE declaracao_importacao ALTER COLUMN frete_total_dolares TYPE varchar(255) USING frete_total_dolares::varchar(255);
ALTER TABLE declaracao_importacao ALTER COLUMN frete_total_moeda TYPE varchar(255) USING frete_total_moeda::varchar(255);
ALTER TABLE declaracao_importacao ALTER COLUMN frete_total_reais TYPE varchar(255) USING frete_total_reais::varchar(255);
ALTER TABLE declaracao_importacao ALTER COLUMN importador_codigo_tipo TYPE varchar(255) USING importador_codigo_tipo::varchar(255);
ALTER TABLE declaracao_importacao ALTER COLUMN importador_cpf_representante_legal TYPE varchar(255) USING importador_cpf_representante_legal::varchar(255);
ALTER TABLE declaracao_importacao ALTER COLUMN importador_endereco_bairro TYPE varchar(255) USING importador_endereco_bairro::varchar(255);
ALTER TABLE declaracao_importacao ALTER COLUMN importador_endereco_cep TYPE varchar(255) USING importador_endereco_cep::varchar(255);
ALTER TABLE declaracao_importacao ALTER COLUMN importador_endereco_complemento TYPE varchar(255) USING importador_endereco_complemento::varchar(255);
ALTER TABLE declaracao_importacao ALTER COLUMN importador_endereco_logradouro TYPE varchar(255) USING importador_endereco_logradouro::varchar(255);
ALTER TABLE declaracao_importacao ALTER COLUMN importador_endereco_municipio TYPE varchar(255) USING importador_endereco_municipio::varchar(255);
ALTER TABLE declaracao_importacao ALTER COLUMN importador_endereco_numero TYPE varchar(255) USING importador_endereco_numero::varchar(255);
ALTER TABLE declaracao_importacao ALTER COLUMN importador_endereco_uf TYPE varchar(255) USING importador_endereco_uf::varchar(255);
ALTER TABLE declaracao_importacao ALTER COLUMN importador_nome TYPE varchar(255) USING importador_nome::varchar(255);
ALTER TABLE declaracao_importacao ALTER COLUMN importador_nome_representante_legal TYPE varchar(255) USING importador_nome_representante_legal::varchar(255);
ALTER TABLE declaracao_importacao ALTER COLUMN importador_numero TYPE varchar(255) USING importador_numero::varchar(255);
ALTER TABLE declaracao_importacao ALTER COLUMN importador_numero_telefone TYPE varchar(255) USING importador_numero_telefone::varchar(255);
ALTER TABLE declaracao_importacao ALTER COLUMN informacao_complementar TYPE varchar(255) USING informacao_complementar::varchar(255);
ALTER TABLE declaracao_importacao ALTER COLUMN local_descarga_total_dolares TYPE varchar(255) USING local_descarga_total_dolares::varchar(255);
ALTER TABLE declaracao_importacao ALTER COLUMN local_descarga_total_reais TYPE varchar(255) USING local_descarga_total_reais::varchar(255);
ALTER TABLE declaracao_importacao ALTER COLUMN local_embarque_total_dolares TYPE varchar(255) USING local_embarque_total_dolares::varchar(255);
ALTER TABLE declaracao_importacao ALTER COLUMN local_embarque_total_reais TYPE varchar(255) USING local_embarque_total_reais::varchar(255);
ALTER TABLE declaracao_importacao ALTER COLUMN modalidade_despacho_codigo TYPE varchar(255) USING modalidade_despacho_codigo::varchar(255);
ALTER TABLE declaracao_importacao ALTER COLUMN modalidade_despacho_nome TYPE varchar(255) USING modalidade_despacho_nome::varchar(255);
ALTER TABLE declaracao_importacao ALTER COLUMN numero_di TYPE varchar(255) USING numero_di::varchar(255);
ALTER TABLE declaracao_importacao ALTER COLUMN operacao_fundap TYPE varchar(255) USING operacao_fundap::varchar(255);
ALTER TABLE declaracao_importacao ALTER COLUMN seguro_moeda_negociada_codigo TYPE varchar(255) USING seguro_moeda_negociada_codigo::varchar(255);
ALTER TABLE declaracao_importacao ALTER COLUMN seguro_moeda_negociada_nome TYPE varchar(255) USING seguro_moeda_negociada_nome::varchar(255);
ALTER TABLE declaracao_importacao ALTER COLUMN seguro_total_dolares TYPE varchar(255) USING seguro_total_dolares::varchar(255);
ALTER TABLE declaracao_importacao ALTER COLUMN seguro_total_moeda_negociada TYPE varchar(255) USING seguro_total_moeda_negociada::varchar(255);
ALTER TABLE declaracao_importacao ALTER COLUMN seguro_total_reais TYPE varchar(255) USING seguro_total_reais::varchar(255);
ALTER TABLE declaracao_importacao ALTER COLUMN sequencial_retificacao TYPE varchar(255) USING sequencial_retificacao::varchar(255);
ALTER TABLE declaracao_importacao ALTER COLUMN situacao_entrega_carga TYPE varchar(255) USING situacao_entrega_carga::varchar(255);
ALTER TABLE declaracao_importacao ALTER COLUMN tipo_declaracao_codigo TYPE varchar(255) USING tipo_declaracao_codigo::varchar(255);
ALTER TABLE declaracao_importacao ALTER COLUMN tipo_declaracao_nome TYPE varchar(255) USING tipo_declaracao_nome::varchar(255);
ALTER TABLE declaracao_importacao ALTER COLUMN total_adicoes TYPE varchar(255) USING total_adicoes::varchar(255);
ALTER TABLE declaracao_importacao ALTER COLUMN urf_despacho_codigo TYPE varchar(255) USING urf_despacho_codigo::varchar(255);
ALTER TABLE declaracao_importacao ALTER COLUMN urf_despacho_nome TYPE varchar(255) USING urf_despacho_nome::varchar(255);
ALTER TABLE declaracao_importacao ALTER COLUMN valor_total_multa_a_recolher_ajustado TYPE varchar(255) USING valor_total_multa_a_recolher_ajustado::varchar(255);
ALTER TABLE declaracao_importacao ALTER COLUMN via_transporte_codigo TYPE varchar(255) USING via_transporte_codigo::varchar(255);
ALTER TABLE declaracao_importacao ALTER COLUMN via_transporte_multimodal TYPE varchar(255) USING via_transporte_multimodal::varchar(255);
ALTER TABLE declaracao_importacao ALTER COLUMN via_transporte_nome TYPE varchar(255) USING via_transporte_nome::varchar(255);
ALTER TABLE declaracao_importacao ALTER COLUMN via_transporte_nome_transportador TYPE varchar(255) USING via_transporte_nome_transportador::varchar(255);
ALTER TABLE declaracao_importacao ALTER COLUMN via_transporte_pais_transportador_codigo TYPE varchar(255) USING via_transporte_pais_transportador_codigo::varchar(255);
ALTER TABLE declaracao_importacao ALTER COLUMN via_transporte_pais_transportador_nome TYPE varchar(255) USING via_transporte_pais_transportador_nome::varchar(255);
ALTER TABLE declaracao_importacao ALTER COLUMN documento_instrucao_despacho_id TYPE varchar(255) USING documento_instrucao_despacho_id::varchar(255);
ALTER TABLE declaracao_importacao ALTER COLUMN embalagem_id TYPE varchar(255) USING embalagem_id::varchar(255);
ALTER TABLE declaracao_importacao ALTER COLUMN icms_id TYPE varchar(255) USING icms_id::varchar(255);
ALTER TABLE declaracao_importacao ALTER COLUMN pagamento_id TYPE varchar(255) USING pagamento_id::varchar(255);
/*Declaração Importacao*/